Rename RCT to AE and change package name
appfolio/react-native-camera pull request #5
Opened 2017-07-07 21:11 UTC by dvicory

2017-07-07 21:32 UTC, dvicory commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Android] App usually crashes on launch](https://trello.com/c/syAvD39p/249-android-app-usually-crashes-on-launch)

2017-07-07 21:38 UTC, jonkessler requested changes
Search for "rctcamera" case-insensitive in the project.. there are still some references.

2017-07-07 21:38 UTC, jonkessler commented on README.md
> +  - Add `import com.appfolio.AECamera.AECameraPackage;` to the imports at the top of the file
`com.appfolio.react.camera.CameraPackage` ?

2017-07-07 21:38 UTC, jonkessler commented on README.md
> +  - Add `new AECameraPackage()` to the list returned by the `getPackages()` method. Add a comma to the previous item if there's already something there.
`new CameraPackage()`?

2017-07-07 21:38 UTC, jonkessler commented on ios/AECamera.h
> +- (id)initWithManager:(AECameraManager*)manager bridge:(RCTBridge *)bridge;
Need a space between `AECameraManager` and `*`.

2017-07-07 21:38 UTC, jonkessler commented on ios/AECamera.m
> +- (id)initWithManager:(AECameraManager*)manager bridge:(RCTBridge *)bridge
Missing space.

2017-07-13 17:36 UTC, jonkessler approved these changes

2017-07-13 17:43 UTC, merged